#!/bin/bash

# This is a buld file for Minatauro clusters in Barcelona Supercomputing Center (BSC).
# Each modules contains special version of libraries that are needed for compiling 
# and building ZSim+DRAMsim3 simulation platform. 

module purge

module load intel 
module load HDF5 PYTHON/2.7.3  SCONS/2.5.1 
module load gcc/7.2.0 
module load libelf
module load CMAKE/3.7.2 

#export LC_ALL="en_US.UTF-8"

# we need to set some PATHs for compiling ZSim
export LIBCONFIG_HOME=/home/bsc18/bsc18278/zsim/sim-env/libconfig-1.5/
export PINPATH=/home/bsc18/bsc18278/zsim/sim-env/pin/
export HDF5_HOME=/home/bsc18/bsc18278/zsim/sim-env/hdf5-1.8.16/

export DRAMSIM3PATH=/home/bsc18/bsc18278/zsimdramsim3/acmSimulation/DRAMsim3_mt/
export RAMULATORPATH=/home/bsc18/bsc18278/zsimdramsim3/acmSimulation/Ramulator/ramulator/

export LD_LIBRARY_PATH=$LIBCONFIG_HOME/lib:$HDF5_HOME/lib:$LD_LIBRARY_PATH


scons -c

scons -j16 --d
